services:
  531bbb:
    build: .
    container_name: 531bbb
    restart: unless-stopped
    ports:
      - "8126:8126"
    volumes:
      - 531bbb-data:/data
    environment:
      - DB_PATH=/data/531bbb.db
    x-casaos:
      envs:
        - container: DB_PATH
          description:
            en_us: SQLite database path

volumes:
  531bbb-data:
    driver: local
